# Generated by Django 2.1.5 on 2020-01-31 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import idea.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('service_location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('education_degree', models.CharField(blank=True, choices=[('diploma', 'دیپلم'), ('bachelour', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('doc', 'دکتری'), ('post-doc', 'پسادکترا')], default='diploma', max_length=100, null=True)),
                ('education_field', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('internet_address', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('physical_address', models.TextField(blank=True, default='', null=True)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('body', models.TextField(blank=True, default='', null=True)),
                ('category', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('state', models.CharField(choices=[('submit', 'ثبت اولیه'), ('rejected', 'رد شده'), ('rejected-incomplete', 'رد شده-نقص اطلاعات'), ('under-review', 'ارزیابی علمی'), ('submit', 'ثبت اولیه'), ('tk', 'تکمیل کاربرگ\u200cها'), ('dfkk', 'داوری فنی کسب و کار'), ('bka', 'برگزاری کارگروه ارزیابی'), ('tndsp', 'طرح نتایج در شورای پذیرش'), ('de', 'دریافت اعتبار')], default='submit', max_length=100)),
                ('state_text', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('code', models.CharField(default=idea.models.code_generator, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
