# Generated by Django 2.1.5 on 2019-08-11 12:00

from django.db import migrations, models
import utils.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190811_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=utils.ftp.UploadToPathAndRename('public_html/events')),
        ),
    ]
