# Generated by Django 2.1.5 on 2020-04-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200306_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='student_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='teacher_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular'), ('thesis', 'Thesis')], default='Regular', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='university',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
