# Generated by Django 2.1.5 on 2020-07-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_brief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='brief',
        ),
    ]
