# Generated by Django 2.1.5 on 2019-08-13 12:18

from django.db import migrations, models
import django.db.models.deletion
import utils.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atlas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('body', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=utils.ftp.UploadToPathAndRename('public_html/atlas'))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atlases', to='atlas.AtlasCategory')),
            ],
            options={
                'verbose_name': 'اطلس',
                'verbose_name_plural': 'اطلس\u200cها',
            },
        ),
    ]
