# Generated by Django 2.1.5 on 2019-12-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_atlas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atlas',
            options={'verbose_name': 'جنگ\u200cافزار', 'verbose_name_plural': 'جنگ\u200cافزار\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='atlascategory',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
    ]
