# Generated by Django 2.1.5 on 2020-06-18 20:37

from django.db import migrations, models
import utils.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0003_auto_20191216_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atlas',
            options={'verbose_name': 'سامانه\u200c', 'verbose_name_plural': 'سامانه\u200cها'},
        ),
        migrations.AddField(
            model_name='atlas',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.ftp.UploadToPathAndRename('public_html/atlas')),
        ),
    ]
