# Generated by Django 2.1.5 on 2020-06-27 16:01

from django.db import migrations, models
import utils.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0004_auto_20200619_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlascategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=utils.ftp.UploadToPathAndRename('public_html/atlas')),
        ),
    ]
