# Generated by Django 2.1.5 on 2020-07-10 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0005_atlascategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atlas',
            name='created',
        ),
        migrations.RemoveField(
            model_name='atlas',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='atlas',
            name='removed',
        ),
        migrations.RemoveField(
            model_name='atlascategory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='atlascategory',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='atlascategory',
            name='removed',
        ),
    ]
