# Generated by Django 2.1.5 on 2019-12-16 13:13

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import utils.ftp


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('body', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=utils.ftp.UploadToPathAndRename('public_html/info'))),
            ],
            options={
                'verbose_name': 'داده\u200cنگاری',
                'verbose_name_plural': 'داده\u200cنگاری\u200cها',
            },
        ),
        migrations.CreateModel(
            name='InfographicCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='infographic.InfographicCategory')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.AddField(
            model_name='infographic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='infographic.InfographicCategory'),
        ),
    ]
