# Generated by Django 2.1.5 on 2019-12-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infographic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infographic',
            old_name='body',
            new_name='bottom_text',
        ),
        migrations.AddField(
            model_name='infographic',
            name='top_text',
            field=models.TextField(blank=True),
        ),
    ]
