# Generated by Django 2.1.5 on 2020-07-11 18:06

from django.db import migrations, models
import utils.ftp


class Migration(migrations.Migration):

    dependencies = [
        ('infographic', '0002_auto_20191216_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infographic',
            name='created',
        ),
        migrations.RemoveField(
            model_name='infographic',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='infographic',
            name='removed',
        ),
        migrations.RemoveField(
            model_name='infographiccategory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='infographiccategory',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='infographiccategory',
            name='removed',
        ),
        migrations.AddField(
            model_name='infographiccategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=utils.ftp.UploadToPathAndRename('public_html/info')),
        ),
    ]
