# Generated by Django 2.1.5 on 2019-08-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('unique_code', models.CharField(default='', max_length=15)),
                ('img_url', models.CharField(default='', max_length=400)),
                ('is_active', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_in_mobile_visible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'درگاه',
                'verbose_name_plural': 'درگاه\u200cها',
            },
        ),
    ]
