# Generated by Django 2.1.5 on 2019-08-10 10:09

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20190810_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=book.models.UploadToPathAndRename('public_html/books')),
        ),
    ]
