# Generated by Django 2.1.5 on 2019-08-14 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20190810_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('checkout', 'Checkout'), ('paid', 'Paid'), ('cancel', 'Canceled'), ('payfail', 'Paid Failed'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], default='checkout', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookShopItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookOrder', verbose_name='items')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
