# Generated by Django 2.1.5 on 2019-08-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20190814_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshopitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookshopitem',
            name='order',
        ),
    ]
