# Generated by Django 2.1.5 on 2019-08-14 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20190814_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshopitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.BookOrder', verbose_name='items'),
        ),
    ]
