# Generated by Django 2.1.5 on 2020-02-06 17:48

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_auto_20190815_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='token',
            field=models.CharField(default=utils.utils.code_generator, max_length=30),
        ),
    ]
