# Generated by Django 2.1.5 on 2020-06-18 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.ftp
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to=utils.ftp.UploadToPathAndRename('public_html/magazines'))),
            ],
        ),
        migrations.CreateModel(
            name='MagazineOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('checkout', 'Checkout'), ('paid', 'Paid')], default='checkout', max_length=30)),
                ('token', models.CharField(default=utils.utils.code_generator, max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='magazine',
            options={'verbose_name': 'مجله', 'verbose_name_plural': 'مجله\u200cها'},
        ),
        migrations.AddField(
            model_name='magazine',
            name='author',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='dl_file',
            field=models.FileField(blank=True, null=True, upload_to=utils.ftp.UploadToPathAndRename('public_html/magazines')),
        ),
        migrations.AddField(
            model_name='magazine',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=utils.ftp.UploadToPathAndRename('public_html/magazines')),
        ),
        migrations.AddField(
            model_name='magazine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='magazine',
            name='year',
            field=models.IntegerField(default=1390),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='magazineorder',
            name='magazine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magazine.Magazine'),
        ),
        migrations.AddField(
            model_name='magazineorder',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
