# Generated by Django 2.1.5 on 2020-06-18 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_auto_20200619_0236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magazinecategory',
            options={'verbose_name': 'دسته مجله', 'verbose_name_plural': 'دسته مجله'},
        ),
        migrations.AlterModelOptions(
            name='magazineorder',
            options={'verbose_name': 'فاکتور خرید', 'verbose_name_plural': 'فاکتورهای خرید'},
        ),
        migrations.AddField(
            model_name='magazine',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='removed',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='magazinecategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazinecategory',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='magazinecategory',
            name='removed',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
